In [30]:
# help(np.zeros)

In [31]:
# 1.Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
myvec = np.zeros(shape = 10,dtype = int)
myvec[4] = 1
myvec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [46]:
# help(np.arange)

In [44]:
# 2.Create a vector with values ranging from 10 to 49
myvec3 = np.arange(start = 10,stop = 50,step = 1,dtype = int)
myvec3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [71]:
# 3.Create a 3x3 matrix with values ranging from 0 to 8
mymatrix = np.array(object = [[0,1,2],
                  [3,4,5],
                  [6,7,8]],dtype = int)
print("Matrix is of type",str(mymatrix.shape[0])+"X"+str(mymatrix.shape[1]))
mymatrix

Matrix is of type 3X3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
# help(np.full)
# help(np.array)
# help(np.where)

In [80]:
# 4.Find indices of non-zero elements from [1,2,0,0,4,0]
myvec4 = np.array(object = [1,2,0,0,4,0],dtype = int)
myindexes = np.where(myvec4 > 0)
myindexes

(array([0, 1, 4], dtype=int32),)

In [101]:
# # dir(np)
# help(np.random.randint)

In [100]:
# 5.Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(1)
myarr1 = np.random.randint(low = 0,high = 150,size = (10,10),dtype = int)
print("Minimum Value is ",myarr1.min())
print("Maximum Value is ",myarr1.max())
myarr1

Minimum Value is  1
Maximum Value is  149


array([[ 37, 140,  72, 137, 133,  79, 144, 129,  71, 134],
       [ 25,  20, 101, 146, 139, 142,  50,  68,  96,  86],
       [141, 137,   7,  63,  61,  22,  57,   1, 128,  60],
       [  8, 141, 115, 121,  30,  71, 131, 149,  49,  57],
       [  3,  24,  43,  76,  26,  52,  80, 109, 115,  41],
       [ 15,  64,  25, 111, 135,  26, 104,  22,   9, 126],
       [ 23, 125, 100,  57,  83, 136,  32,  10,  23, 143],
       [ 87,  25,  92,  74,  46,  65, 113,  77,   3, 128],
       [  6,  52,   2,  76, 149,   7,  77,  75,  76,  43],
       [ 20,  30,  36, 103,   7,  45,  57,  96,  13,  10]])

In [104]:
# 6.Create a random vector of size 30 and find the mean value.
np.random.seed(1)
myvec5 = np.random.randint(low = 0,high = 200,size = 30,dtype = int)
print("Mean of 30 values is",myvec5.mean())
myvec5

Mean of 30 values is 102.1


array([ 37, 140,  72, 137, 133,  79, 192, 144, 129,  71, 134,  25, 178,
        20, 101, 146, 139, 156, 157, 142,  50,  68,  96,  86, 141, 137,
         7,  63,  61,  22])